import {
  collection,
  doc,
  writeBatch,
  getDocs,
  query,
  where,
} from 'firebase/firestore';
import { db } from './firebase';
import {
  Shop,
  Product,
  Order,
  MerchantAccount,
  SellerApplication,
  ShopMember,
  DeliveryAssignment,
  Category,
  PlatformSettings,
} from '../types';

export const DEMO_USERS = {
  admin: {
    uid: 'demo_user_admin',
    email: 'admin@dailymart.com',
    name: 'DailyMart Admin',
    phone: '+91 99000 00001',
    role: 'admin' as const,
  },
  shopOwner: {
    uid: 'demo_user_shopowner',
    email: 'shopowner@dailymart.com',
    name: 'Ramesh Sharma (Owner)',
    phone: '+91 99000 00002',
    role: 'shop_owner' as const,
  },
  delivery: {
    uid: 'demo_user_delivery',
    email: 'delivery@dailymart.com',
    name: 'Sunil Kumar (Delivery Partner)',
    phone: '+91 99000 00003',
    role: 'delivery_staff' as const,
  },
  customer: {
    uid: 'demo_user_customer',
    email: 'user@dailymart.com',
    name: 'Yashwant Verma',
    phone: '+91 99000 00004',
    role: 'customer' as const,
  },
};

export const DEMO_SHOPS: Shop[] = [
  {
    id: 'demo-shop-shree-krishna',
    name: 'Shree Krishna General Store',
    ownerId: DEMO_USERS.shopOwner.uid,
    ownerName: DEMO_USERS.shopOwner.name,
    category: 'Groceries & Daily Staples',
    description: 'Trusted neighborhood grocery store with farm-fresh grains, pulses, dairy & packaged essentials.',
    phone: '+91 99000 00002',
    address: 'Shop 4, Jairaj Nagar, Tukum',
    city: 'Chandrapur',
    pincode: '442401',
    latitude: 19.9707,
    longitude: 79.2967,
    isOpen: true,
    verificationStatus: 'VERIFIED',
    isActive: true,
    rating: 4.8,
    totalRatings: 184,
    deliveryRadius: 12,
    deliveryFee: 20,
    freeDeliveryAbove: 299,
    minOrder: 99,
    estimatedDeliveryTime: '20–30 min',
    image: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=600',
    tags: ['Groceries', 'Atta & Rice', 'Cooking Oil', 'Daily Staples'],
    gstin: '27AABCS1429B1ZB',
    pan: 'AABCS1429B',
    isDemoData: true,
    environment: 'demo',
  },
  {
    id: 'demo-shop-fresh-basket',
    name: 'Fresh Basket Organics',
    ownerId: 'demo_user_shopowner_2',
    ownerName: 'Sunita Patel',
    category: 'Fresh Fruits & Vegetables',
    description: 'Farm-picked fresh fruits, leafy greens and organic vegetables delivered within 25 minutes.',
    phone: '+91 99000 00020',
    address: 'Plot 12, Gandhi Chowk, Ramnagar',
    city: 'Chandrapur',
    pincode: '442401',
    latitude: 19.9650,
    longitude: 79.3010,
    isOpen: true,
    verificationStatus: 'VERIFIED',
    isActive: true,
    rating: 4.9,
    totalRatings: 92,
    deliveryRadius: 12,
    deliveryFee: 15,
    freeDeliveryAbove: 199,
    minOrder: 79,
    estimatedDeliveryTime: '15–25 min',
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=600',
    tags: ['Organic', 'Vegetables', 'Fruits', 'Fresh Greens'],
    gstin: '27AABCF9921D1Z8',
    pan: 'AABCF9921D',
    isDemoData: true,
    environment: 'demo',
  },
  {
    id: 'demo-shop-city-mart',
    name: 'City Daily Mart Supermarket',
    ownerId: 'demo_user_shopowner_3',
    ownerName: 'Vikram Singh',
    category: 'General Supermarket',
    description: 'Complete home supermarket covering household cleaning, snacks, beverages and dairy products.',
    phone: '+91 99000 00030',
    address: 'Near Stadium, Civil Lines',
    city: 'Chandrapur',
    pincode: '442401',
    latitude: 19.9740,
    longitude: 79.2880,
    isOpen: true,
    verificationStatus: 'VERIFIED',
    isActive: true,
    rating: 4.6,
    totalRatings: 310,
    deliveryRadius: 12,
    deliveryFee: 25,
    freeDeliveryAbove: 349,
    minOrder: 120,
    estimatedDeliveryTime: '25–35 min',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600',
    tags: ['Supermarket', 'Snacks', 'Beverages', 'Cleaning'],
    gstin: '27AAACD5512E1Z2',
    pan: 'AAACD5512E',
    isDemoData: true,
    environment: 'demo',
  },
];

export const DEMO_PRODUCTS: Product[] = [
  // Shop 1: Shree Krishna Products
  {
    id: 'demo-prod-rice',
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    name: 'India Gate Basmati Rice (Premium)',
    description: 'Aged long-grain aromatic basmati rice for biryani and daily meals.',
    category: 'Rice & Grains',
    price: 180,
    mrp: 210,
    unit: '1 kg',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500',
    stockQuantity: 45,
    lowStockThreshold: 10,
    inStock: true,
    isActive: true,
    isAvailable: true,
    isFeatured: true,
    isDemoData: true,
    environment: 'demo',
  },
  {
    id: 'demo-prod-atta',
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    name: 'Aashirvaad Shudh Chakki Atta',
    description: '100% whole wheat flour with natural fiber for soft rotis.',
    category: 'Flour & Atta',
    price: 65,
    mrp: 75,
    unit: '1 kg',
    image: 'https://images.unsplash.com/photo-1627485937980-221c88ac04f9?w=500',
    stockQuantity: 50,
    lowStockThreshold: 15,
    inStock: true,
    isActive: true,
    isAvailable: true,
    isFeatured: true,
    isDemoData: true,
    environment: 'demo',
  },
  {
    id: 'demo-prod-toor-dal',
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    name: 'Tata Sampann Unpolished Toor Dal',
    description: 'Protein-rich unpolished toor dal for everyday nutritious dal tadka.',
    category: 'Pulses',
    price: 145,
    mrp: 165,
    unit: '1 kg',
    image: 'https://images.unsplash.com/photo-1596797882870-8c33deeac224?w=500',
    stockQuantity: 30,
    lowStockThreshold: 8,
    inStock: true,
    isActive: true,
    isAvailable: true,
    isDemoData: true,
    environment: 'demo',
  },
  {
    id: 'demo-prod-sunflower-oil',
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    name: 'Fortune Sunlite Refined Sunflower Oil',
    description: 'Light and healthy sunflower oil enriched with vitamins A & D.',
    category: 'Cooking Oil',
    price: 145,
    mrp: 160,
    unit: '1 litre',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500',
    stockQuantity: 28,
    lowStockThreshold: 10,
    inStock: true,
    isActive: true,
    isAvailable: true,
    isDemoData: true,
    environment: 'demo',
  },
  {
    id: 'demo-prod-amul-milk',
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    name: 'Amul Taaza Homogenised Toned Milk',
    description: 'Fresh toned pasteurized milk for morning tea, coffee & cereal.',
    category: 'Dairy',
    price: 30,
    mrp: 30,
    unit: '500 ml',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500',
    stockQuantity: 60,
    lowStockThreshold: 20,
    inStock: true,
    isActive: true,
    isAvailable: true,
    isFeatured: true,
    isDemoData: true,
    environment: 'demo',
  },
  {
    id: 'demo-prod-tata-tea',
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    name: 'Tata Tea Premium Desh Ki Chai',
    description: 'Rich taste and refreshing aroma crafted from fine Assam tea leaves.',
    category: 'Beverages',
    price: 125,
    mrp: 140,
    unit: '250 g',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500',
    stockQuantity: 40,
    lowStockThreshold: 10,
    inStock: true,
    isActive: true,
    isAvailable: true,
    isDemoData: true,
    environment: 'demo',
  },

  // Shop 2: Fresh Basket Organics Products
  {
    id: 'demo-prod-organic-apples',
    shopId: 'demo-shop-fresh-basket',
    shopName: 'Fresh Basket Organics',
    name: 'Shimla Royal Apple (Crisp & Sweet)',
    description: 'Hand-sorted fresh crispy sweet apples packed with natural antioxidants.',
    category: 'Fresh Fruits',
    price: 160,
    mrp: 190,
    unit: '1 kg (4-5 pcs)',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500',
    stockQuantity: 25,
    lowStockThreshold: 5,
    inStock: true,
    isActive: true,
    isAvailable: true,
    isFeatured: true,
    isDemoData: true,
    environment: 'demo',
  },
  {
    id: 'demo-prod-fresh-tomatoes',
    shopId: 'demo-shop-fresh-basket',
    shopName: 'Fresh Basket Organics',
    name: 'Farm Fresh Desi Tomatoes',
    description: 'Juicy ripe red tomatoes directly procured from local greenhouses.',
    category: 'Fresh Vegetables',
    price: 35,
    mrp: 45,
    unit: '1 kg',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500',
    stockQuantity: 40,
    lowStockThreshold: 10,
    inStock: true,
    isActive: true,
    isAvailable: true,
    isDemoData: true,
    environment: 'demo',
  },
  {
    id: 'demo-prod-spinach',
    shopId: 'demo-shop-fresh-basket',
    shopName: 'Fresh Basket Organics',
    name: 'Organic Fresh Spinach (Palak)',
    description: 'Washed and pesticide-free tender green spinach leaves.',
    category: 'Fresh Vegetables',
    price: 25,
    mrp: 30,
    unit: '250 g bunch',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500',
    stockQuantity: 30,
    lowStockThreshold: 8,
    inStock: true,
    isActive: true,
    isAvailable: true,
    isDemoData: true,
    environment: 'demo',
  },

  // Shop 3: City Daily Mart Supermarket Products
  {
    id: 'demo-prod-surf-excel',
    shopId: 'demo-shop-city-mart',
    shopName: 'City Daily Mart Supermarket',
    name: 'Surf Excel Matic Front Load Detergent',
    description: 'High efficiency stain removal liquid detergent for modern washing machines.',
    category: 'Cleaning & Household',
    price: 240,
    mrp: 275,
    unit: '1 litre',
    image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?w=500',
    stockQuantity: 35,
    lowStockThreshold: 5,
    inStock: true,
    isActive: true,
    isAvailable: true,
    isFeatured: true,
    isDemoData: true,
    environment: 'demo',
  },
  {
    id: 'demo-prod-oreo',
    shopId: 'demo-shop-city-mart',
    shopName: 'City Daily Mart Supermarket',
    name: 'Cadbury Oreo Original Vanilla Cookies',
    description: 'Crunchy chocolate sandwich cookies filled with rich sweet vanilla cream.',
    category: 'Snacks & Biscuits',
    price: 40,
    mrp: 45,
    unit: '120 g pack',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500',
    stockQuantity: 65,
    lowStockThreshold: 15,
    inStock: true,
    isActive: true,
    isAvailable: true,
    isDemoData: true,
    environment: 'demo',
  },
];

export const DEMO_CATEGORIES: Category[] = [
  { id: 'cat-groceries', name: 'Groceries & Staples', slug: 'groceries-staples', icon: '🌾', image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300', displayOrder: 1, isActive: true },
  { id: 'cat-vegetables', name: 'Vegetables & Fruits', slug: 'vegetables-fruits', icon: '🥦', image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=300', displayOrder: 2, isActive: true },
  { id: 'cat-dairy', name: 'Dairy & Breakfast', slug: 'dairy-breakfast', icon: '🥛', image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300', displayOrder: 3, isActive: true },
  { id: 'cat-snacks', name: 'Snacks & Beverages', slug: 'snacks-beverages', icon: '🍪', image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=300', displayOrder: 4, isActive: true },
  { id: 'cat-household', name: 'Household & Cleaning', slug: 'household-cleaning', icon: '🧼', image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?w=300', displayOrder: 5, isActive: true },
  { id: 'cat-personal', name: 'Personal Care', slug: 'personal-care', icon: '🧴', image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=300', displayOrder: 6, isActive: true },
];

export const DEMO_ORDERS: Order[] = [
  // 1. ORDER_PLACED (NEW) - Shop Owner needs to Accept / Reject
  {
    id: 'demo-order-1-new',
    orderId: 'DM-1001',
    customerId: DEMO_USERS.customer.uid,
    customerName: DEMO_USERS.customer.name,
    customerPhone: DEMO_USERS.customer.phone,
    deliveryAddress: 'Flat 402, Green Orchid Apartments, Tukum Road, Chandrapur',
    landmark: 'Opposite Central Park',
    customerLatitude: 19.9712,
    customerLongitude: 79.2980,
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    shopOwnerId: DEMO_USERS.shopOwner.uid,
    items: [
      { productId: 'demo-prod-rice', name: 'India Gate Basmati Rice', price: 180, quantity: 1, unit: '1 kg', image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500', subtotal: 180 },
      { productId: 'demo-prod-atta', name: 'Aashirvaad Shudh Chakki Atta', price: 65, quantity: 2, unit: '1 kg', image: 'https://images.unsplash.com/photo-1627485937980-221c88ac04f9?w=500', subtotal: 130 },
    ],
    subtotal: 310,
    deliveryFee: 20,
    discount: 0,
    totalAmount: 330,
    paymentMethod: 'COD',
    paymentStatus: 'PENDING',
    orderStatus: 'ORDER_PLACED',
    estimatedDeliveryTime: '25–35 min',
    notes: 'Please ring bell twice upon arrival.',
    statusHistory: [
      {
        status: 'ORDER_PLACED',
        timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
        updatedBy: DEMO_USERS.customer.name,
        actorRole: 'CUSTOMER',
        reason: 'Customer placed order via DailyMart marketplace.',
      },
    ],
    isDemoData: true,
    environment: 'demo',
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },

  // 2. SHOP_ACCEPTED - Shop Owner confirmed, getting ready to pack
  {
    id: 'demo-order-2-accepted',
    orderId: 'DM-1002',
    customerId: DEMO_USERS.customer.uid,
    customerName: DEMO_USERS.customer.name,
    customerPhone: DEMO_USERS.customer.phone,
    deliveryAddress: 'House 18, Ramnagar Colony, Chandrapur',
    customerLatitude: 19.9690,
    customerLongitude: 79.2950,
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    shopOwnerId: DEMO_USERS.shopOwner.uid,
    items: [
      { productId: 'demo-prod-toor-dal', name: 'Tata Sampann Unpolished Toor Dal', price: 145, quantity: 1, unit: '1 kg', image: 'https://images.unsplash.com/photo-1596797882870-8c33deeac224?w=500', subtotal: 145 },
      { productId: 'demo-prod-amul-milk', name: 'Amul Taaza Milk', price: 30, quantity: 2, unit: '500 ml', image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500', subtotal: 60 },
    ],
    subtotal: 205,
    deliveryFee: 20,
    discount: 0,
    totalAmount: 225,
    paymentMethod: 'ONLINE',
    paymentStatus: 'PAID',
    orderStatus: 'SHOP_ACCEPTED',
    estimatedDeliveryTime: '20–30 min',
    statusHistory: [
      {
        status: 'ORDER_PLACED',
        timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
        updatedBy: DEMO_USERS.customer.name,
        actorRole: 'CUSTOMER',
      },
      {
        status: 'SHOP_ACCEPTED',
        previousStatus: 'ORDER_PLACED',
        timestamp: new Date(Date.now() - 10 * 60000).toISOString(),
        updatedBy: DEMO_USERS.shopOwner.name,
        actorRole: 'SHOP_OWNER',
        reason: 'Order confirmed and scheduled for packing.',
      },
    ],
    isDemoData: true,
    environment: 'demo',
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
  },

  // 3. PREPARING (PACKING) - Shop Owner is packing items
  {
    id: 'demo-order-3-preparing',
    orderId: 'DM-1003',
    customerId: DEMO_USERS.customer.uid,
    customerName: DEMO_USERS.customer.name,
    customerPhone: DEMO_USERS.customer.phone,
    deliveryAddress: 'Row House 4, Civil Lines, Chandrapur',
    customerLatitude: 19.9720,
    customerLongitude: 79.2940,
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    shopOwnerId: DEMO_USERS.shopOwner.uid,
    items: [
      { productId: 'demo-prod-sunflower-oil', name: 'Fortune Sunflower Oil', price: 145, quantity: 1, unit: '1 litre', image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500', subtotal: 145 },
      { productId: 'demo-prod-tata-tea', name: 'Tata Tea Premium', price: 125, quantity: 1, unit: '250 g', image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500', subtotal: 125 },
    ],
    subtotal: 270,
    deliveryFee: 20,
    discount: 0,
    totalAmount: 290,
    paymentMethod: 'ONLINE',
    paymentStatus: 'PAID',
    orderStatus: 'PREPARING',
    estimatedDeliveryTime: '15–25 min',
    statusHistory: [
      { status: 'ORDER_PLACED', timestamp: new Date(Date.now() - 25 * 60000).toISOString(), updatedBy: DEMO_USERS.customer.name, actorRole: 'CUSTOMER' },
      { status: 'SHOP_ACCEPTED', previousStatus: 'ORDER_PLACED', timestamp: new Date(Date.now() - 20 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'PREPARING', previousStatus: 'SHOP_ACCEPTED', timestamp: new Date(Date.now() - 12 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER', reason: 'Packing groceries in eco-friendly bag.' },
    ],
    isDemoData: true,
    environment: 'demo',
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60000).toISOString(),
  },

  // 4. READY_FOR_PICKUP - Ready for Shop Owner to assign delivery partner
  {
    id: 'demo-order-4-ready',
    orderId: 'DM-1004',
    customerId: DEMO_USERS.customer.uid,
    customerName: DEMO_USERS.customer.name,
    customerPhone: DEMO_USERS.customer.phone,
    deliveryAddress: 'Flat 101, Shanti Niketan, Tukum',
    customerLatitude: 19.9705,
    customerLongitude: 79.2975,
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    shopOwnerId: DEMO_USERS.shopOwner.uid,
    items: [
      { productId: 'demo-prod-rice', name: 'India Gate Basmati Rice', price: 180, quantity: 1, unit: '1 kg', image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500', subtotal: 180 },
    ],
    subtotal: 180,
    deliveryFee: 20,
    discount: 0,
    totalAmount: 200,
    paymentMethod: 'COD',
    paymentStatus: 'PENDING',
    orderStatus: 'READY_FOR_PICKUP',
    estimatedDeliveryTime: '15–20 min',
    statusHistory: [
      { status: 'ORDER_PLACED', timestamp: new Date(Date.now() - 30 * 60000).toISOString(), updatedBy: DEMO_USERS.customer.name, actorRole: 'CUSTOMER' },
      { status: 'SHOP_ACCEPTED', previousStatus: 'ORDER_PLACED', timestamp: new Date(Date.now() - 25 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'PREPARING', previousStatus: 'SHOP_ACCEPTED', timestamp: new Date(Date.now() - 18 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'READY_FOR_PICKUP', previousStatus: 'PREPARING', timestamp: new Date(Date.now() - 8 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER', reason: 'Order bagged and ready for dispatch.' },
    ],
    isDemoData: true,
    environment: 'demo',
    createdAt: new Date(Date.now() - 30 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60000).toISOString(),
  },

  // 5. ASSIGNED_TO_DELIVERY - Assigned to Sunil Kumar (Delivery Partner to Accept)
  {
    id: 'demo-order-5-assigned',
    orderId: 'DM-1005',
    customerId: DEMO_USERS.customer.uid,
    customerName: DEMO_USERS.customer.name,
    customerPhone: DEMO_USERS.customer.phone,
    deliveryAddress: 'Plot 45, Near Hanuman Mandir, Tukum',
    customerLatitude: 19.9715,
    customerLongitude: 79.2990,
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    shopOwnerId: DEMO_USERS.shopOwner.uid,
    deliveryStaffId: DEMO_USERS.delivery.uid,
    deliveryStaffName: DEMO_USERS.delivery.name,
    deliveryStaffPhone: DEMO_USERS.delivery.phone,
    items: [
      { productId: 'demo-prod-atta', name: 'Aashirvaad Shudh Chakki Atta', price: 65, quantity: 2, unit: '1 kg', image: 'https://images.unsplash.com/photo-1627485937980-221c88ac04f9?w=500', subtotal: 130 },
      { productId: 'demo-prod-amul-milk', name: 'Amul Taaza Milk', price: 30, quantity: 1, unit: '500 ml', image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500', subtotal: 30 },
    ],
    subtotal: 160,
    deliveryFee: 20,
    discount: 0,
    totalAmount: 180,
    paymentMethod: 'COD',
    paymentStatus: 'PENDING',
    orderStatus: 'ASSIGNED_TO_DELIVERY',
    estimatedDeliveryTime: '15–20 min',
    statusHistory: [
      { status: 'ORDER_PLACED', timestamp: new Date(Date.now() - 35 * 60000).toISOString(), updatedBy: DEMO_USERS.customer.name, actorRole: 'CUSTOMER' },
      { status: 'SHOP_ACCEPTED', previousStatus: 'ORDER_PLACED', timestamp: new Date(Date.now() - 30 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'PREPARING', previousStatus: 'SHOP_ACCEPTED', timestamp: new Date(Date.now() - 20 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'READY_FOR_PICKUP', previousStatus: 'PREPARING', timestamp: new Date(Date.now() - 10 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'ASSIGNED_TO_DELIVERY', previousStatus: 'READY_FOR_PICKUP', timestamp: new Date(Date.now() - 5 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER', reason: 'Assigned to delivery staff Sunil Kumar.' },
    ],
    isDemoData: true,
    environment: 'demo',
    createdAt: new Date(Date.now() - 35 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },

  // 6. PICKED_UP - Delivery partner at store, picked up package
  {
    id: 'demo-order-6-pickedup',
    orderId: 'DM-1006',
    customerId: DEMO_USERS.customer.uid,
    customerName: DEMO_USERS.customer.name,
    customerPhone: DEMO_USERS.customer.phone,
    deliveryAddress: 'Flat 203, Galaxy Heights, Ramnagar',
    customerLatitude: 19.9680,
    customerLongitude: 79.2960,
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    shopOwnerId: DEMO_USERS.shopOwner.uid,
    deliveryStaffId: DEMO_USERS.delivery.uid,
    deliveryStaffName: DEMO_USERS.delivery.name,
    deliveryStaffPhone: DEMO_USERS.delivery.phone,
    items: [
      { productId: 'demo-prod-toor-dal', name: 'Tata Sampann Unpolished Toor Dal', price: 145, quantity: 2, unit: '1 kg', image: 'https://images.unsplash.com/photo-1596797882870-8c33deeac224?w=500', subtotal: 290 },
    ],
    subtotal: 290,
    deliveryFee: 20,
    discount: 0,
    totalAmount: 310,
    paymentMethod: 'ONLINE',
    paymentStatus: 'PAID',
    orderStatus: 'PICKED_UP',
    estimatedDeliveryTime: '10–15 min',
    statusHistory: [
      { status: 'ORDER_PLACED', timestamp: new Date(Date.now() - 40 * 60000).toISOString(), updatedBy: DEMO_USERS.customer.name, actorRole: 'CUSTOMER' },
      { status: 'SHOP_ACCEPTED', previousStatus: 'ORDER_PLACED', timestamp: new Date(Date.now() - 35 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'PREPARING', previousStatus: 'SHOP_ACCEPTED', timestamp: new Date(Date.now() - 25 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'READY_FOR_PICKUP', previousStatus: 'PREPARING', timestamp: new Date(Date.now() - 15 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'ASSIGNED_TO_DELIVERY', previousStatus: 'READY_FOR_PICKUP', timestamp: new Date(Date.now() - 12 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'ACCEPTED', previousStatus: 'ASSIGNED_TO_DELIVERY', timestamp: new Date(Date.now() - 10 * 60000).toISOString(), updatedBy: DEMO_USERS.delivery.name, actorRole: 'DELIVERY_STAFF', reason: 'Delivery partner accepted assignment.' },
      { status: 'PICKED_UP', previousStatus: 'ACCEPTED', timestamp: new Date(Date.now() - 4 * 60000).toISOString(), updatedBy: DEMO_USERS.delivery.name, actorRole: 'DELIVERY_STAFF', reason: 'Order collected from store counter.' },
    ],
    isDemoData: true,
    environment: 'demo',
    createdAt: new Date(Date.now() - 40 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60000).toISOString(),
  },

  // 7. OUT_FOR_DELIVERY - On the bike, heading to customer
  {
    id: 'demo-order-7-out',
    orderId: 'DM-1007',
    customerId: DEMO_USERS.customer.uid,
    customerName: DEMO_USERS.customer.name,
    customerPhone: DEMO_USERS.customer.phone,
    deliveryAddress: 'Bunglow 9, VIP Road, Civil Lines',
    customerLatitude: 19.9730,
    customerLongitude: 79.2920,
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    shopOwnerId: DEMO_USERS.shopOwner.uid,
    deliveryStaffId: DEMO_USERS.delivery.uid,
    deliveryStaffName: DEMO_USERS.delivery.name,
    deliveryStaffPhone: DEMO_USERS.delivery.phone,
    items: [
      { productId: 'demo-prod-rice', name: 'India Gate Basmati Rice', price: 180, quantity: 1, unit: '1 kg', image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500', subtotal: 180 },
      { productId: 'demo-prod-sunflower-oil', name: 'Fortune Sunflower Oil', price: 145, quantity: 1, unit: '1 litre', image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500', subtotal: 145 },
    ],
    subtotal: 325,
    deliveryFee: 20,
    discount: 0,
    totalAmount: 345,
    paymentMethod: 'COD',
    paymentStatus: 'PENDING',
    orderStatus: 'OUT_FOR_DELIVERY',
    estimatedDeliveryTime: '5–10 min',
    statusHistory: [
      { status: 'ORDER_PLACED', timestamp: new Date(Date.now() - 45 * 60000).toISOString(), updatedBy: DEMO_USERS.customer.name, actorRole: 'CUSTOMER' },
      { status: 'SHOP_ACCEPTED', previousStatus: 'ORDER_PLACED', timestamp: new Date(Date.now() - 40 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'PREPARING', previousStatus: 'SHOP_ACCEPTED', timestamp: new Date(Date.now() - 30 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'READY_FOR_PICKUP', previousStatus: 'PREPARING', timestamp: new Date(Date.now() - 20 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'ASSIGNED_TO_DELIVERY', previousStatus: 'READY_FOR_PICKUP', timestamp: new Date(Date.now() - 15 * 60000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'PICKED_UP', previousStatus: 'ASSIGNED_TO_DELIVERY', timestamp: new Date(Date.now() - 10 * 60000).toISOString(), updatedBy: DEMO_USERS.delivery.name, actorRole: 'DELIVERY_STAFF' },
      { status: 'OUT_FOR_DELIVERY', previousStatus: 'PICKED_UP', timestamp: new Date(Date.now() - 3 * 60000).toISOString(), updatedBy: DEMO_USERS.delivery.name, actorRole: 'DELIVERY_STAFF', reason: 'Rider on two-wheeler towards destination.' },
    ],
    isDemoData: true,
    environment: 'demo',
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60000).toISOString(),
  },

  // 8. DELIVERED - Completed successfully with cash collected
  {
    id: 'demo-order-8-delivered',
    orderId: 'DM-1008',
    customerId: DEMO_USERS.customer.uid,
    customerName: DEMO_USERS.customer.name,
    customerPhone: DEMO_USERS.customer.phone,
    deliveryAddress: 'Flat 304, Suryakiran Apartments, Tukum',
    customerLatitude: 19.9700,
    customerLongitude: 79.2970,
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    shopOwnerId: DEMO_USERS.shopOwner.uid,
    deliveryStaffId: DEMO_USERS.delivery.uid,
    deliveryStaffName: DEMO_USERS.delivery.name,
    deliveryStaffPhone: DEMO_USERS.delivery.phone,
    items: [
      { productId: 'demo-prod-atta', name: 'Aashirvaad Shudh Chakki Atta', price: 65, quantity: 1, unit: '1 kg', image: 'https://images.unsplash.com/photo-1627485937980-221c88ac04f9?w=500', subtotal: 65 },
      { productId: 'demo-prod-amul-milk', name: 'Amul Taaza Milk', price: 30, quantity: 2, unit: '500 ml', image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500', subtotal: 60 },
    ],
    subtotal: 125,
    deliveryFee: 20,
    discount: 0,
    totalAmount: 145,
    paymentMethod: 'COD',
    paymentStatus: 'COLLECTED',
    orderStatus: 'DELIVERED',
    estimatedDeliveryTime: 'Delivered',
    statusHistory: [
      { status: 'ORDER_PLACED', timestamp: new Date(Date.now() - 3 * 3600000).toISOString(), updatedBy: DEMO_USERS.customer.name, actorRole: 'CUSTOMER' },
      { status: 'SHOP_ACCEPTED', previousStatus: 'ORDER_PLACED', timestamp: new Date(Date.now() - 2.8 * 3600000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'PREPARING', previousStatus: 'SHOP_ACCEPTED', timestamp: new Date(Date.now() - 2.5 * 3600000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'READY_FOR_PICKUP', previousStatus: 'PREPARING', timestamp: new Date(Date.now() - 2.3 * 3600000).toISOString(), updatedBy: DEMO_USERS.shopOwner.name, actorRole: 'SHOP_OWNER' },
      { status: 'PICKED_UP', previousStatus: 'READY_FOR_PICKUP', timestamp: new Date(Date.now() - 2.1 * 3600000).toISOString(), updatedBy: DEMO_USERS.delivery.name, actorRole: 'DELIVERY_STAFF' },
      { status: 'OUT_FOR_DELIVERY', previousStatus: 'PICKED_UP', timestamp: new Date(Date.now() - 2.0 * 3600000).toISOString(), updatedBy: DEMO_USERS.delivery.name, actorRole: 'DELIVERY_STAFF' },
      { status: 'DELIVERED', previousStatus: 'OUT_FOR_DELIVERY', timestamp: new Date(Date.now() - 1.8 * 3600000).toISOString(), updatedBy: DEMO_USERS.delivery.name, actorRole: 'DELIVERY_STAFF', reason: 'Delivered in hand. ₹145 cash collected.' },
    ],
    isDemoData: true,
    environment: 'demo',
    createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 1.8 * 3600000).toISOString(),
  },

  // 9. CANCELLED - Cancelled by customer before dispatch
  {
    id: 'demo-order-9-cancelled',
    orderId: 'DM-1009',
    customerId: DEMO_USERS.customer.uid,
    customerName: DEMO_USERS.customer.name,
    customerPhone: DEMO_USERS.customer.phone,
    deliveryAddress: 'House 8, Market Yard, Chandrapur',
    customerLatitude: 19.9670,
    customerLongitude: 79.2980,
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    shopOwnerId: DEMO_USERS.shopOwner.uid,
    items: [
      { productId: 'demo-prod-tata-tea', name: 'Tata Tea Premium', price: 125, quantity: 1, unit: '250 g', image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500', subtotal: 125 },
    ],
    subtotal: 125,
    deliveryFee: 20,
    discount: 0,
    totalAmount: 145,
    paymentMethod: 'ONLINE',
    paymentStatus: 'REFUNDED',
    orderStatus: 'CANCELLED',
    cancellationReason: 'Customer selected wrong delivery address by mistake.',
    estimatedDeliveryTime: 'Cancelled',
    statusHistory: [
      { status: 'ORDER_PLACED', timestamp: new Date(Date.now() - 5 * 3600000).toISOString(), updatedBy: DEMO_USERS.customer.name, actorRole: 'CUSTOMER' },
      { status: 'CANCELLED', previousStatus: 'ORDER_PLACED', timestamp: new Date(Date.now() - 4.9 * 3600000).toISOString(), updatedBy: DEMO_USERS.customer.name, actorRole: 'CUSTOMER', reason: 'Customer requested cancellation: wrong address.' },
    ],
    isDemoData: true,
    environment: 'demo',
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 4.9 * 3600000).toISOString(),
  },

  // 10. DELIVERY_FAILED - Rider reached address but customer was unreachable
  {
    id: 'demo-order-10-failed',
    orderId: 'DM-1010',
    customerId: DEMO_USERS.customer.uid,
    customerName: DEMO_USERS.customer.name,
    customerPhone: DEMO_USERS.customer.phone,
    deliveryAddress: 'Flat 502, Orchid Heights, Tukum',
    customerLatitude: 19.9700,
    customerLongitude: 79.2995,
    shopId: 'demo-shop-shree-krishna',
    shopName: 'Shree Krishna General Store',
    shopOwnerId: DEMO_USERS.shopOwner.uid,
    deliveryStaffId: DEMO_USERS.delivery.uid,
    deliveryStaffName: DEMO_USERS.delivery.name,
    deliveryStaffPhone: DEMO_USERS.delivery.phone,
    items: [
      { productId: 'demo-prod-rice', name: 'India Gate Basmati Rice', price: 180, quantity: 1, unit: '1 kg', image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500', subtotal: 180 },
    ],
    subtotal: 180,
    deliveryFee: 20,
    discount: 0,
    totalAmount: 200,
    paymentMethod: 'COD',
    paymentStatus: 'FAILED',
    orderStatus: 'DELIVERY_FAILED',
    failureReason: 'Customer phone was unreachable and door locked after 3 attempts.',
    estimatedDeliveryTime: 'Delivery Failed',
    statusHistory: [
      { status: 'ORDER_PLACED', timestamp: new Date(Date.now() - 6 * 3600000).toISOString(), updatedBy: DEMO_USERS.customer.name, actorRole: 'CUSTOMER' },
      { status: 'OUT_FOR_DELIVERY', timestamp: new Date(Date.now() - 5.5 * 3600000).toISOString(), updatedBy: DEMO_USERS.delivery.name, actorRole: 'DELIVERY_STAFF' },
      { status: 'DELIVERY_FAILED', previousStatus: 'OUT_FOR_DELIVERY', timestamp: new Date(Date.now() - 5.2 * 3600000).toISOString(), updatedBy: DEMO_USERS.delivery.name, actorRole: 'DELIVERY_STAFF', reason: 'Customer door locked; multiple phone calls went unanswered.' },
    ],
    isDemoData: true,
    environment: 'demo',
    createdAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 5.2 * 3600000).toISOString(),
  },
];

export const DEMO_SELLER_APPLICATIONS: SellerApplication[] = [
  {
    id: 'demo-app-green-garden',
    applicationId: 'DM-REG-2041',
    applicantUid: 'demo_user_applicant',
    applicantUserId: 'demo_user_applicant',
    applicantName: 'Vikrant Deshmukh',
    applicantPhone: '+91 99000 00050',
    applicantEmail: 'vikrant.spices@example.com',
    shopName: 'Green Garden Fresh & Spices',
    category: 'Groceries & Daily Staples',
    address: 'Near Old Cotton Market, Main Road',
    city: 'Chandrapur',
    pincode: '442401',
    deliveryRadius: 12,
    gstin: '27AAACE1234F1Z9',
    pan: 'AAACE1234F',
    latitude: 19.9685,
    longitude: 79.2930,
    documents: [
      'GST Registration Certificate (Form REG-06)',
      'Shop & Establishment License (Gumasta)',
      'FSSAI Food Safety License',
    ],
    status: 'PENDING',
    isDemoData: true,
    environment: 'demo',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

export const DEMO_SHOP_MEMBERS: ShopMember[] = [
  {
    id: `${DEMO_USERS.shopOwner.uid}_demo-shop-shree-krishna`,
    shopId: 'demo-shop-shree-krishna',
    userId: DEMO_USERS.shopOwner.uid,
    name: DEMO_USERS.shopOwner.name,
    phone: DEMO_USERS.shopOwner.phone,
    email: DEMO_USERS.shopOwner.email,
    role: 'SHOP_OWNER',
    status: 'ACTIVE',
    permissions: ['PRODUCT_MANAGE', 'ORDER_MANAGE', 'EMPLOYEE_MANAGE', 'DELIVERY_MANAGE'],
    isDemoData: true,
    environment: 'demo',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: `${DEMO_USERS.delivery.uid}_demo-shop-shree-krishna`,
    shopId: 'demo-shop-shree-krishna',
    shopOwnerId: DEMO_USERS.shopOwner.uid,
    userId: DEMO_USERS.delivery.uid,
    name: DEMO_USERS.delivery.name,
    phone: DEMO_USERS.delivery.phone,
    email: DEMO_USERS.delivery.email,
    role: 'DELIVERY_STAFF',
    vehicleType: 'BIKE',
    status: 'ACTIVE',
    permissions: [],
    isDemoData: true,
    environment: 'demo',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const DEMO_MERCHANT_ACCOUNTS: MerchantAccount[] = [
  {
    shopId: 'demo-shop-shree-krishna',
    businessName: 'Shree Krishna General Store',
    ownerName: 'Ramesh Sharma',
    phone: '+91 99000 00002',
    email: 'shopowner@dailymart.com',
    businessAddress: 'Shop 4, Jairaj Nagar, Tukum, Chandrapur',
    gstin: '27AABCS1429B1ZB',
    pan: 'AABCS1429B',
    bankAccountHolder: 'Shree Krishna General Store',
    bankName: 'State Bank of India',
    ifsc: 'SBIN0001234',
    accountNumberMasked: '****4821',
    status: 'VERIFIED',
    payoutStatus: 'ACTIVE',
    platformCommissionRate: 5,
    connectedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

/**
 * Idempotently seeds the complete DailyMart demo dataset into Firestore.
 * Overwrites ONLY documents flagged with `isDemoData: true`.
 */
export async function seedDemoMarketplace(): Promise<{
  success: boolean;
  shopsCount: number;
  productsCount: number;
  ordersCount: number;
  message: string;
}> {
  try {
    const batch = writeBatch(db);

    // 1. Users
    for (const [, user] of Object.entries(DEMO_USERS)) {
      batch.set(
        doc(db, 'users', user.uid),
        {
          id: user.uid,
          uid: user.uid,
          name: user.name,
          email: user.email,
          phone: user.phone,
          role: user.role,
          roles: {
            customer: true,
            merchant: user.role === 'shop_owner',
            delivery: user.role === 'delivery_staff',
            admin: user.role === 'admin',
          },
          status: 'ACTIVE',
          address: 'Jairaj Nagar, Tukum, Chandrapur',
          latitude: 19.9707,
          longitude: 79.2967,
          shopId: user.role === 'shop_owner' || user.role === 'delivery_staff' ? 'demo-shop-shree-krishna' : null,
          isDemoData: true,
          environment: 'demo',
          createdAt: new Date().toISOString(),
        },
        { merge: true }
      );
    }

    // 2. Admin record for adminUsers collection
    batch.set(
      doc(db, 'adminUsers', DEMO_USERS.admin.uid),
      {
        id: DEMO_USERS.admin.uid,
        name: DEMO_USERS.admin.name,
        email: DEMO_USERS.admin.email,
        role: 'SUPER_ADMIN',
        isActive: true,
        isDemoData: true,
        environment: 'demo',
        createdAt: new Date().toISOString(),
      },
      { merge: true }
    );

    // 3. Shops
    for (const shop of DEMO_SHOPS) {
      batch.set(doc(db, 'shops', shop.id), shop, { merge: true });
    }

    // 4. Products
    for (const product of DEMO_PRODUCTS) {
      batch.set(doc(db, 'products', product.id), product, { merge: true });
    }

    // 5. Categories
    for (const category of DEMO_CATEGORIES) {
      batch.set(doc(db, 'categories', category.id), category, { merge: true });
    }

    // 6. Orders
    for (const order of DEMO_ORDERS) {
      batch.set(doc(db, 'orders', order.id), order, { merge: true });
    }

    // 7. Seller Applications
    for (const app of DEMO_SELLER_APPLICATIONS) {
      batch.set(doc(db, 'sellerApplications', app.id), app, { merge: true });
    }

    // 8. Shop Members
    for (const member of DEMO_SHOP_MEMBERS) {
      batch.set(doc(db, 'shopMembers', member.id), member, { merge: true });
    }

    // 9. Merchant Accounts
    for (const acc of DEMO_MERCHANT_ACCOUNTS) {
      batch.set(doc(db, 'merchantAccounts', acc.shopId), acc, { merge: true });
    }

    // 10. Platform Settings
    const defaultSettings: PlatformSettings = {
      platformName: 'DailyMart Hyper-Local',
      supportEmail: 'support@dailymart.com',
      supportPhone: '+91 7122 100100',
      defaultDeliveryRadiusKm: 12,
      defaultCommissionRate: 5,
      defaultDeliveryFee: 20,
      minOrderAmount: 99,
      isCodEnabled: true,
      autoCancelTimeoutMins: 30,
      updatedAt: new Date().toISOString(),
    };
    batch.set(doc(db, 'platformSettings', 'main'), defaultSettings, { merge: true });

    await batch.commit();

    return {
      success: true,
      shopsCount: DEMO_SHOPS.length,
      productsCount: DEMO_PRODUCTS.length,
      ordersCount: DEMO_ORDERS.length,
      message: 'Demo dataset successfully seeded into Firestore with 3 shops, 11 products, and 10 workflow orders.',
    };
  } catch (error) {
    console.error('Error seeding demo marketplace data:', error);
    return {
      success: false,
      shopsCount: 0,
      productsCount: 0,
      ordersCount: 0,
      message: error instanceof Error ? error.message : 'Unknown error during demo seeding',
    };
  }
}
